### ISSUE TITLE
Will you be releasing builds for mac?

### ISSUE THREAD

**Issue by iandoesallthethings** [warpspeedchic/Snookey3#4]
Hello! 

I see the source code under releases, but I don't know how to build python apps myself. Any chance you would be willing/able to release a build for MacOS? 

Thanks,
Ian

**Comment by warpspeedchic** [comment]
As much as I'd like to do it, I don't have a MacOS machine, which would be needed both for testing and for building to even be possible. I will try to explore some possibilities, but can't make any promises right now.
